export const ADD_FCILITIES = "ADD_FCILITIES"
export const DELETE_FCILITIES = "DELETE_FCILITIES"
export const UPDATE_FCILITIES = "UPDATE_FCILITIES"
export const LOADING_FCILITIES = "LOADINGE_FCILITIES"
export const GET_FCILITIES = "GET_FCILITIES"


export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DECREMENT_COUNTER = "DECREMENT_COUNTER"

export const ADD_PRODUCT = "ADD_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const LOADING_PRODUCT = "LOADINGE_PRODUCT"
export const ERROR_PRODUCT = "ERROR_PRODUCT"
export const GET_PRODUCT = "GET_PRODUCT"

export const GET_SHOP = "GET_SHOP"

export const GET_SHOPDETAIL = "GET_SHOPDETAIL"