export const ADD_FCILITIES = "ADD_FCILITIES"
export const DELETE_FCILITIES = "DELETE_FCILITIES"
export const UPDATE_FCILITIES = "UPDATE_FCILITIES"

export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DECREMENT_COUNTER = "DECREMENT_COUNTER"
